import { useEffect, useRef, useState } from 'react';
import { Play, Pause, SkipBack, SkipForward, Scissors, Share2, Download, X, Trash2, Crosshair } from 'lucide-react';
import { useStore } from '../store';
import { clock, seek } from '../lib/playback';
import { clipURL, portableClip, validateClip, download } from '../lib/clips';
import { exportWebM } from '../lib/exportWebM';
import { framePair, playerSpeed } from '../lib/parseSkillCorner';
export function formatTime(seconds){const ms=Math.round(Math.max(0,seconds)*1000);return `${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms%60000/1000)).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`;}
export default function VideoControls({match}) {
  const clips=useStore(s=>s.clips),selected=useStore(s=>s.selected),locked=useStore(s=>s.exporting);const [time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[loop,setLoop]=useState(false),[start,setStart]=useState(0),[end,setEnd]=useState(Math.min(7,match.duration)),[windowStart,setWindowStart]=useState(0),[name,setName]=useState(''),[message,setMessage]=useState(''),[modal,setModal]=useState(null),[progress,setProgress]=useState(0);const dialog=useRef(),abort=useRef();
  useEffect(()=>{const timer=setInterval(()=>{setTime(clock.time);setPlaying(clock.playing);},100);return()=>{clearInterval(timer);abort.current?.abort();};},[]);
  useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
  useEffect(()=>{function keys(event){if(event.target.closest('input,select,textarea,button,dialog')||clock.exporting)return;if(event.code==='Space'){event.preventDefault();toggle();}if(event.key==='ArrowLeft'){event.preventDefault();scrub(clock.time-5);}if(event.key==='ArrowRight'){event.preventDefault();scrub(clock.time+5);}}window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[match]);
  function toggle(){if(clock.exporting)return;const lower=clock.range?.start??0,upper=clock.range?.end??match.duration;if(clock.time>=upper)seek(lower,match.duration);clock.playing=!clock.playing;setPlaying(clock.playing);}
  function scrub(value){clock.range=null;seek(value,match.duration);setTime(clock.time);}
  function trimStart(value){if(!Number.isFinite(value))return;const v=Math.max(0,Math.min(match.duration-.001,value));if(v<windowStart||v+10>windowStart+30)setWindowStart(Math.max(0,Math.min(match.duration-30,v-5)));setStart(v);setEnd(Math.min(match.duration,Math.max(v+.001,Math.min(end,v+10))));}
  function trimEnd(value){if(!Number.isFinite(value))return;setEnd(Math.max(start+.001,Math.min(match.duration,start+10,value)));}
  function mark(){const s=Math.min(clock.time,match.duration-.001);setWindowStart(Math.max(0,Math.min(match.duration-30,s-5)));setStart(s);setEnd(Math.min(match.duration,s+Math.max(.001,end-start)));}
  function makeClip(){try{return {...validateClip(start,end,match.duration),name:name.trim()||`Sequence ${clips.length+1}`};}catch(error){setMessage(error.message);return null;}}
  function replay(clip){clock.range={start:clip.start,end:clip.end};seek(clip.start,match.duration);clock.playing=true;setPlaying(true);setTime(clip.start);}
  async function record(){setMessage('');setProgress(0);abort.current=new AbortController();useStore.getState().patch({exporting:true});try{await exportWebM(match,modal,{signal:abort.current.signal,onProgress:setProgress});setMessage('WebM downloaded.');}catch(error){setMessage(error.name==='AbortError'?'Export cancelled.':error.message);}finally{abort.current=null;useStore.getState().patch({exporting:false});}}
  const windowEnd=Math.min(match.duration,windowStart+30),windowDuration=windowEnd-windowStart;const pair=framePair(match,time),speedKmh=playerSpeed(match,selected,pair),owner=match.players[match.owners[pair.a]],current=match.players[selected];
  return <div className="grid lg:grid-cols-[minmax(0,1fr)_320px] gap-5 mt-5">
    <section className="hud-panel p-5 space-y-5"><div className="flex flex-wrap items-center gap-2"><button className="primary" disabled={locked} onClick={toggle}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?'Pause':'Play'}</button><button aria-label="Back five seconds" disabled={locked} onClick={()=>scrub(clock.time-5)}><SkipBack size={16}/>5s</button><button aria-label="Forward five seconds" disabled={locked} onClick={()=>scrub(clock.time+5)}>5s<SkipForward size={16}/></button><span className="font-mono text-sm ml-auto">{formatTime(time)} <span className="text-slate-400">/ {formatTime(match.duration)}</span></span><select aria-label="Playback speed" disabled={locked} value={speed} onChange={event=>{const v=Number(event.target.value);setSpeed(v);clock.speed=v;}}>{[.25,.5,1,2,4].map(s=><option key={s} value={s}>{s}×</option>)}</select></div>
    <div><label className="sr-only" htmlFor="timeline">Match timeline</label><input disabled={locked} id="timeline" className="w-full accent-emerald-300" type="range" min="0" max={match.duration} step=".001" value={time} aria-valuetext={formatTime(time)} onChange={event=>scrub(Number(event.target.value))}/><div className="flex justify-between text-xs text-slate-400 font-mono mt-2">{[0,.25,.5,.75,1].map(f=><span key={f}>{formatTime(match.duration*f).slice(0,5)}</span>)}</div></div>
    <div className="flex flex-wrap items-center gap-4 border-t border-slate-700/50 pt-4 text-xs text-slate-300"><label className="flex items-center gap-2"><input type="checkbox" disabled={locked} checked={loop} onChange={e=>{setLoop(e.target.checked);clock.loop=e.target.checked;}}/>Loop</label><span>Period {match.periods[pair.a]} · match clock {formatTime(match.matchTimes[pair.a])}</span>{clock.range&&<button disabled={locked} onClick={()=>{clock.range=null;setMessage('Full match playback restored.');}}>Return to match</button>}{pair.stale&&<span className="text-amber-300">Tracking gap · positions unavailable</span>}</div>
    <div className="grid sm:grid-cols-2 gap-3"><div className="stat"><span>Selected player</span><strong>#{current?.number} · {current?.name}</strong><small>{speedKmh==null?'Speed unavailable':`${speedKmh.toFixed(1)} km/h · frame-to-frame estimate`}</small></div><div className="stat"><span>Possession</span><strong>{pair.stale?'Unavailable':owner?`#${owner.number} · ${owner.name}`:'No identified player'}</strong><small>Reported by the tracking source</small></div></div>
    <div><div className="flex justify-between items-center"><h3>Clip library</h3><span className="text-xs text-slate-400">{clips.length} saved in this session</span></div>{clips.length===0?<p className="text-slate-400 text-sm py-5">Mark a moment and save your first sequence.</p>:<div className="space-y-3 mt-3">{clips.map(clip=><div key={clip.id} className="clip-row"><div className="min-w-0"><strong className="break-words text-sm">{clip.name}</strong><div className="font-mono text-xs text-slate-400 mt-1">{formatTime(clip.start)} → {formatTime(clip.end)}</div></div><div className="flex gap-2 shrink-0"><button aria-label={`Replay ${clip.name}`} disabled={locked} onClick={()=>replay(clip)}><Play size={15}/></button><button aria-label={`Share ${clip.name}`} disabled={locked} onClick={()=>setModal(clip)}><Share2 size={15}/></button><button aria-label={`Delete ${clip.name}`} disabled={locked} onClick={()=>useStore.getState().removeClip(clip.id)}><Trash2 size={15}/></button></div></div>)}</div>}</div></section>
    <section className="hud-panel p-5"><div className="eyebrow">Sequence editor</div><h3 className="mt-2 text-lg">Every movement matters.</h3><p className="text-xs text-slate-400 mt-2 mb-5">Trim up to 10 seconds. Share a link, a portable clip, or a video.</p><label className="field-label" htmlFor="clip-name">Clip name</label><input id="clip-name" disabled={locked} maxLength={80} className="w-full" placeholder="e.g. Third-man run" value={name} onChange={e=>setName(e.target.value)}/>
    <div className="grid grid-cols-2 gap-3 mt-4"><div><label className="field-label" htmlFor="trim-start">Start · seconds</label><input id="trim-start" className="w-full" type="number" min="0" max={match.duration-.001} step=".001" disabled={locked} value={Number(start.toFixed(3))} onChange={e=>trimStart(e.target.valueAsNumber)}/></div><div><label className="field-label" htmlFor="trim-end">End · seconds</label><input id="trim-end" className="w-full" type="number" min={start+.001} max={Math.min(match.duration,start+10)} step=".001" disabled={locked} value={Number(end.toFixed(3))} onChange={e=>trimEnd(e.target.valueAsNumber)}/></div></div>
    <p className="text-xs text-slate-400 mt-5">Trim window · {formatTime(windowStart).slice(0,5)}–{formatTime(windowEnd).slice(0,5)}</p><div className="dual-trimmer mt-2 mb-3"><div className="trim-track"/><div className="trim-fill" style={{left:`${(start-windowStart)/windowDuration*100}%`,width:`${(end-start)/windowDuration*100}%`}}/><input className="handle start" aria-label="Clip start handle" type="range" min={windowStart} max={windowEnd} step=".001" value={start} disabled={locked} onChange={e=>trimStart(Number(e.target.value))}/><input className="handle end" aria-label="Clip end handle" type="range" min={windowStart} max={windowEnd} step=".001" value={end} disabled={locked} onChange={e=>trimEnd(Number(e.target.value))}/></div><div className="flex justify-between text-xs font-mono text-emerald-200"><span>{formatTime(start)}</span><span>{(end-start).toFixed(3)}s</span><span>{formatTime(end)}</span></div>
    <button className="w-full mt-5" disabled={locked} onClick={mark}><Crosshair size={16}/>Set start at playhead</button><div className="grid grid-cols-2 gap-2 mt-3"><button disabled={locked} onClick={()=>{const clip=makeClip();if(clip)replay(clip);}}><Play size={15}/>Preview</button><button disabled={locked} className="primary" onClick={()=>{const clip=makeClip();if(clip){useStore.getState().saveClip(clip);setMessage('Clip saved.');}}}><Scissors size={15}/>Save</button></div><button className="w-full mt-3" disabled={locked} onClick={()=>{const clip=makeClip();if(clip)setModal(clip);}}><Share2 size={15}/>Share / export</button><p role="status" aria-live="polite" className="text-xs text-amber-200 mt-4 break-words">{message}</p></section>
    <dialog ref={dialog} onCancel={e=>{if(locked){e.preventDefault();abort.current?.abort();}else setModal(null);}} onClose={()=>{if(!locked)setModal(null);}} className="share-modal"><div className="flex justify-between items-center"><h3>Share your sequence</h3><button aria-label="Close share dialog" disabled={locked} onClick={()=>setModal(null)}><X size={17}/></button></div>{modal&&<><p className="text-sm text-slate-400 mt-3">{modal.name} · {(modal.end-modal.start).toFixed(3)} seconds</p><label className="field-label mt-5" htmlFor="share-url">Timestamp link</label><input id="share-url" className="w-full" readOnly value={clipURL(match,modal,window.location.href)} onFocus={e=>e.target.select()}/><p className="text-xs text-slate-400 mt-2">Recipients need this hosted app and the same match imported. A local localhost link works only on your computer.</p><button className="w-full mt-4" disabled={locked} onClick={()=>{download(new Blob([JSON.stringify(portableClip(match,modal))],{type:'application/json'}),'touchline-clip.json');setMessage('Portable clip downloaded.');}}><Download size={16}/>Download portable JSON clip</button><p className="text-xs text-slate-400 mt-2">Self-contained: another user can import this file without the full match.</p><button className="primary w-full mt-4" disabled={locked} onClick={record}><Download size={16}/>{locked?`Recording ${Math.round(progress*100)}%`:'Export 3D view as WebM'}</button>{locked&&<button className="w-full mt-2" onClick={()=>abort.current?.abort()}>Cancel recording</button>}<p className="text-xs text-slate-400 mt-2">Records the pitch in real time. Keep this tab visible. HUD labels are excluded.</p><p className="text-xs text-amber-200 mt-3" role="status">{message}</p></>}</dialog>
  </div>;
}
