import { Component, useEffect, useRef, useState } from 'react';
import { Canvas } from '@react-three/fiber';
import { Activity, Upload, Layers, Orbit, Video, AlertTriangle, FileJson } from 'lucide-react';
import Pitch3D from './components/Pitch3D';
import TrackingScene from './components/TrackingScene';
import VideoControls from './components/VideoControls';
import { useStore } from './store';
import { createDemo } from './lib/demo';
import { readClipURL, validateClip } from './lib/clips';
import { clock, seek } from './lib/playback';
class SceneBoundary extends Component {state={error:null};static getDerivedStateFromError(error){return {error};}render(){return this.state.error?<div className="p-12 text-amber-200">3D rendering failed. Enable WebGL / hardware acceleration and reload. {this.state.error.message}</div>:this.props.children;}}
export default function App(){const state=useStore(),[metadata,setMetadata]=useState(null),[metadataName,setMetadataName]=useState(''),[help,setHelp]=useState(false);const worker=useRef();
  useEffect(()=>{state.load(createDemo());return()=>worker.current?.terminate();},[]);
  useEffect(()=>{if(!state.match)return;try{const clip=readClipURL(state.match,window.location.hash);if(clip){clock.range=clip;seek(clip.start,state.match.duration);}}catch(error){state.patch({error:error.message});}},[state.match]);
  async function parse(text,meta,range){worker.current?.terminate();state.patch({busy:true,error:''});const w=new Worker(new URL('./lib/parse.worker.js',import.meta.url),{type:'module'});worker.current=w;
    w.onmessage=({data})=>{w.terminate();if(data.error){state.patch({busy:false,error:data.error});return;}try{if(range)validateClip(range.start,range.end,data.match.duration);state.load(data.match);if(range){clock.range=range;seek(range.start,data.match.duration);}state.patch({busy:false});}catch(error){state.patch({busy:false,error:error.message});}};w.onerror=()=>{w.terminate();state.patch({busy:false,error:'The parsing worker failed. Check the file and try again.'});};w.postMessage({tracking:text,metadata:meta||{}});
  }
  async function importTracking(file){if(!file)return;try{if(file.size>250*1024*1024)throw new Error('File exceeds 250 MiB. Use a smaller match file or a portable clip.');state.patch({busy:true,error:''});const text=await file.text();if(text.trimStart().startsWith('{')){let portable;try{portable=JSON.parse(text);}catch{}if(portable?.format==='touchline-clip-v1'){await parse(portable.tracking,portable.metadata,portable.range);return;}}await parse(text,metadata);}catch(error){state.patch({busy:false,error:error.message});}}
  async function importMetadata(file){if(!file)return;try{const meta=JSON.parse(await file.text());if(!meta||typeof meta!=='object'||Array.isArray(meta))throw new Error('Select a match metadata JSON object.');setMetadata(meta);setMetadataName(file.name);state.patch({error:''});}catch(error){state.patch({error:error.message});}}
  async function bundled(){try{state.patch({busy:true,error:''});const res=await fetch('/data/manifest.json');if(!res.ok)throw new Error('Run npm run data first, or import metadata and tracking files above.');const manifest=await res.json();const [metaRes,trackingRes]=await Promise.all([fetch('/data/'+manifest.metadata),fetch('/data/'+manifest.tracking)]);if(!metaRes.ok||!trackingRes.ok)throw new Error('Bundled match files are missing.');const meta=await metaRes.json();setMetadata(meta);setMetadataName(manifest.metadata);await parse(await trackingRes.text(),meta);}catch(error){state.patch({busy:false,error:error.message});}}
  const disabled=state.busy||state.exporting;
  return <main className="min-h-screen bg-hud text-slate-100"><header className="border-b border-slate-700/50"><div className="max-w-[1440px] mx-auto px-5 md:px-8 py-5 flex items-center gap-3"><div className="brand"><Activity size={23}/></div><div><h1 className="text-xl font-semibold tracking-tight">touchline<span className="text-emerald-200">.</span></h1><p className="text-xs text-slate-400">3D tracking studio</p></div><span className="ml-auto text-xs tracking-widest text-slate-400 hidden sm:block">US SOCCER × COLORSTACK</span></div></header>
  <div className="max-w-[1440px] mx-auto p-5 md:p-8"><div className="flex flex-wrap justify-between gap-4 items-center mb-6"><div><div className="eyebrow">Match intelligence / Workspace</div><h2 className="text-2xl tracking-tight mt-2">{state.match?.title||'Loading workspace'}</h2></div><div className="flex flex-wrap gap-2"><label className={`file-button ${disabled?'locked':''}`}><FileJson size={16}/>Metadata<input className="sr-only" disabled={disabled} type="file" accept=".json" onChange={e=>{importMetadata(e.target.files[0]);e.target.value='';}}/></label><label className={`file-button ${disabled?'locked':''}`}><Upload size={16}/>Import tracking / clip<input className="sr-only" disabled={disabled} type="file" accept=".json,.jsonl" onChange={e=>{importTracking(e.target.files[0]);e.target.value='';}}/></label><button disabled={disabled} onClick={bundled}>Load bundled match</button><button onClick={()=>setHelp(!help)} aria-expanded={help}>How to use</button></div></div>
  {help&&<section className="hud-panel p-5 mb-5 text-sm text-slate-300 space-y-2"><h3>First-time walkthrough</h3><p>1. Run the data download helper and choose Load bundled match, or select the match metadata first, then import tracking.</p><p>2. Play, scrub, change speed, and switch cameras. Free Orbit supports drag and wheel zoom.</p><p>3. Choose a player to follow and inspect speed. Drag the clip handles or type exact start/end seconds.</p><p>4. Preview and save a clip. Use Share / export to download a portable clip or a WebM.</p><p>Space toggles playback; arrow keys seek five seconds when not editing a field.</p></section>}
  {metadataName&&<p className="text-xs text-slate-400 mb-3 break-words">Metadata: {metadataName}</p>}
  {state.error&&<div role="alert" className="notice"><AlertTriangle size={17}/>{state.error}</div>}
  {state.match&&<><div className="hud-panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 p-4 border-b border-slate-700/50"><div className="flex flex-wrap gap-2">{[['tactical',Layers,'Tactical'],['orbit',Orbit,'Free orbit'],['follow',Video,'Player follow']].map(([value,Icon,label])=><button key={value} disabled={disabled} aria-pressed={state.camera===value} className={state.camera===value?'selected':''} onClick={()=>state.patch({camera:value})}><Icon size={15}/>{label}</button>)}</div><div className="flex flex-wrap items-center gap-3 text-xs text-slate-300"><span className="flex items-center gap-2"><i className="w-2 h-2 rounded-full bg-blue-300"/>Home</span><span className="flex items-center gap-2"><i className="w-2 h-2 rounded-full bg-orange-300"/>Away</span><span className="source-badge">{state.match.id==='synthetic-demo'?'SYNTHETIC DEMO':`${state.match.sourceFps.toFixed(1)} FPS SOURCE`}</span></div></div><div className="scene-wrap"><SceneBoundary key={state.loadKey}><Canvas shadows dpr={[1,1.5]} camera={{position:[0,110,.01],fov:48,near:.1,far:400}} gl={{antialias:true,preserveDrawingBuffer:true}} fallback={<p className="p-8">WebGL unavailable. Enable hardware acceleration in your browser.</p>}><color attach="background" args={['#0c1624']}/><Pitch3D pitch={state.match.pitch}/><TrackingScene key={state.loadKey} match={state.match}/></Canvas></SceneBoundary>{state.busy&&<div className="loading" role="status">Parsing tracking data…</div>}</div><div className="p-4 flex flex-wrap gap-5 items-center border-t border-slate-700/50 text-xs"><label className="flex flex-wrap items-center gap-2 min-w-0 max-w-full">Selected player<select className="w-full sm:w-auto" disabled={disabled} value={state.selected} onChange={e=>state.patch({selected:Number(e.target.value)})}>{state.match.players.map(p=><option key={p.id} value={p.index}>#{p.number} · {p.name} ({p.team})</option>)}</select></label><label className="flex gap-2 items-center"><input disabled={disabled} type="checkbox" checked={state.trails} onChange={e=>state.patch({trails:e.target.checked})}/>Motion trails</label><label className="flex gap-2 items-center"><input disabled={disabled} type="checkbox" checked={state.numbers} onChange={e=>state.patch({numbers:e.target.checked})}/>Jersey labels</label><span className="text-slate-400 ml-auto">{state.match.pitch.length} × {state.match.pitch.width} m</span></div></div>{state.match.warnings.map(w=><p key={w} className="text-xs text-amber-200 mt-3">{w}</p>)}<VideoControls key={state.loadKey} match={state.match}/></>}
  <footer className="mt-7 flex flex-wrap justify-between gap-2 text-xs text-slate-400"><span>{state.match?.id==='synthetic-demo'?'Synthetic demo · Illustrative positions':'Tracking data: SkillCorner'}</span><span>Local processing · No tracking upload to a server</span></footer></div></main>;
}
